name: Deploy to PyPI

on:
  release:
    types: [ published, edited ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: |
        python -m pip install pip --upgrade
        pip install poetry
        poetry config virtualenvs.prefer-active-python true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: poetry update
    - name: Assert Version Correctness
      run: |
        TOML_VER=$(poetry version | awk -F' ' '{ print $2 }')
        echo toml "$TOML_VER"
        GIT_VER=${{ github.event.release.tag_name }}
        echo git "$GIT_VER"
        [[ "$TOML_VER" == "$GIT_VER" ]]
        echo "__version__ = \"$GIT_VER\"" > yellowbox_statsd/_version.py
    - name: Publish
      env:
        PYPI_USERNAME: ${{ secrets.pypi_user }}
        PYPI_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        poetry publish -u "$PYPI_USERNAME" -p "$PYPI_PASSWORD" --build
    - name: Upload Binaries as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: dist
    - name: Upload Binaries to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true